edition = "2018"
fn_args_density = "Vertical"
imports_layout = "Vertical"
max_width = 120
merge_imports = true
reorder_impl_items = true
report_todo = "Always"
struct_lit_single_line = false
unstable_features = true
use_field_init_shorthand = true # stringifying makes wrapping chain-method-calls
version = "Two"
